#!/usr/bin/env python3
"""Add Spanish and Tagalog translations for all animal names in manifest.json"""
import json

# Comprehensive translation table - manually curated for accuracy
translations = {
    "cow": {"es": "Vaca", "tl": "Baka"},
    "pig": {"es": "Cerdo", "tl": "Baboy"},
    "chicken": {"es": "Pollo", "tl": "Manok"},
    "horse": {"es": "Caballo", "tl": "Kabayo"},
    "goat": {"es": "Cabra", "tl": "Kambing"},
    "sheep": {"es": "Oveja", "tl": "Tupa"},
    "duck": {"es": "Pato", "tl": "Bibe"},
    "turkey": {"es": "Pavo", "tl": "Pabo"},
    "rooster": {"es": "Gallo", "tl": "Tandang"},
    "donkey": {"es": "Burro", "tl": "Asno"},
    "llama": {"es": "Llama", "tl": "Llama"},
    "alpaca": {"es": "Alpaca", "tl": "Alpaca"},
    "rabbit": {"es": "Conejo", "tl": "Kuneho"},
    "goose": {"es": "Ganso", "tl": "Gansa"},
    "guinea_pig": {"es": "Cuy", "tl": "Daga-daga"},
    "hamster": {"es": "Hámster", "tl": "Hamster"},
    "ferret": {"es": "Hurón", "tl": "Furet"},
    "mule": {"es": "Mula", "tl": "Mula"},
    "pony": {"es": "Poni", "tl": "Pony"},
    "pot_bellied_pig": {"es": "Cerdo Vietnamita", "tl": "Baboy na May Malaking Tiyan"},
    "mouse": {"es": "Ratón", "tl": "Daga"},
    "rat": {"es": "Rata", "tl": "Daga"},
    "goldfish": {"es": "Pez Dorado", "tl": "Gintong Isda"},
    "hedgehog": {"es": "Erizo", "tl": "Dagyaw"},
    "wild_boar": {"es": "Jabalí", "tl": "Baboy Ramo"},
    "opossum": {"es": "Zarigüeya", "tl": "Posum"},
    "sugar_glider": {"es": "Petauro del Azúcar", "tl": "Sugar Glider"},
    "vampire_bat": {"es": "Murciélago Vampiro", "tl": "Paniki Bampira"},
    "black_bear": {"es": "Oso Negro", "tl": "Itim na Oso"},
    "brown_bear": {"es": "Oso Pardo", "tl": "Pulang Oso"},
    "white_tailed_deer": {"es": "Venado Cola Blanca", "tl": "Usap"},
    "red_fox": {"es": "Zorro Rojo", "tl": "Pulang Soro"},
    "raccoon": {"es": "Mapache", "tl": "Raccoon"},
    "squirrel": {"es": "Ardilla", "tl": "Bising"},
    "moose": {"es": "Alce", "tl": "Moose"},
    "elk": {"es": "Wapití", "tl": "Elk"},
    "beaver": {"es": "Castor", "tl": "Biber"},
    "porcupine": {"es": "Puercoespín", "tl": "Porcupine"},
    "skunk": {"es": "Mofeta", "tl": "Skunk"},
    "badger": {"es": "Tejón", "tl": "Badger"},
    "chipmunk": {"es": "Ardilla Listada", "tl": "Chipmunk"},
    "mole": {"es": "Topo", "tl": "Tuldok"},
    "stoat": {"es": "Armiño", "tl": "Stoat"},
    "ermine": {"es": "Armiño", "tl": "Ermine"},
    "wolverine": {"es": "Glotón", "tl": "Wolverine"},
    "woodpecker": {"es": "Pájaro Carpintero", "tl": "Picpio"},
    "hawk": {"es": "Halcón", "tl": "Lawin"},
    "falcon": {"es": "Halcón", "tl": "Falcon"},
    "cacomistle": {"es": "Cacomistle", "tl": "Cacomistle"},
    "genet": {"es": "Geneta", "tl": "Genet"},
    "civet": {"es": "Civeta", "tl": "Musang"},
    "gorilla": {"es": "Gorila", "tl": "Gorilya"},
    "chimpanzee": {"es": "Chimpancé", "tl": "Tsimpanse"},
    "orangutan": {"es": "Orangután", "tl": "Orangutan"},
    "sloth": {"es": "Pereza", "tl": "Sloth"},
    "howler_monkey": {"es": "Mono Aullador", "tl": "Unggoy na Sumisigaw"},
    "capuchin_monkey": {"es": "Mono Capuchino", "tl": "Capuchin Monkey"},
    "spider_monkey": {"es": "Mono Araña", "tl": "Spider Monkey"},
    "lemur": {"es": "Lémur", "tl": "Lemur"},
    "tapir": {"es": "Tapir", "tl": "Tapir"},
    "okapi": {"es": "Okapi", "tl": "Okapi"},
    "chameleon": {"es": "Camaleón", "tl": "Kamelyon"},
    "green_iguana": {"es": "Iguana Verde", "tl": "Berde Iguana"},
    "boa_constrictor": {"es": "Boa Constrictor", "tl": "Boa Constrictor"},
    "python": {"es": "Pitón", "tl": "Piton"},
    "poison_dart_frog": {"es": "Rana Dardo Venenosa", "tl": "Poison Dart Frog"},
    "red_eyed_tree_frog": {"es": "Rana de Ojos Rojos", "tl": "Red Eyed Tree Frog"},
    "anteater": {"es": "Oso Hormiguero", "tl": "Anteater"},
    "armadillo": {"es": "Armadillo", "tl": "Armadillo"},
    "kinkajou": {"es": "Kinkajú", "tl": "Kinkajou"},
    "aye_aye": {"es": "Aye Aye", "tl": "Aye Aye"},
    "tarsier": {"es": "Tarsero", "tl": "Tarsier"},
    "fruit_bat": {"es": "Zorro Volador", "tl": "Paniking Prutas"},
    "pangolin": {"es": "Pangolín", "tl": "Pangolin"},
    "bush_baby": {"es": "Gálago", "tl": "Bush Baby"},
    "anaconda": {"es": "Anaconda", "tl": "Anaconda"},
    "koala": {"es": "Koala", "tl": "Koala"},
    "wombat": {"es": "Wombat", "tl": "Wombat"},
    "tasmanian_devil": {"es": "Demonio de Tasmania", "tl": "Tasmanian Devil"},
    "lion": {"es": "León", "tl": "Leon"},
    "elephant": {"es": "Elefante", "tl": "Elepante"},
    "hyena": {"es": "Hiena", "tl": "Hiyena"},
    "aardvark": {"es": "Cerdo Hormiguero", "tl": "Aardvark"},
    "fennec_fox": {"es": "Zorro del Desierto", "tl": "Fennec Fox"},
    "jerboa": {"es": "Jerboa", "tl": "Jerboa"},
    "scorpion": {"es": "Escorpión", "tl": "Alakdan"},
    "gecko": {"es": "Geco", "tl": "Tuko"},
    "polar_bear": {"es": "Oso Polar", "tl": "Polar Bear"},
    "arctic_fox": {"es": "Zorro Ártico", "tl": "Arctic Fox"},
    "arctic_hare": {"es": "Liebre Ártica", "tl": "Arctic Hare"},
    "arctic_wolf": {"es": "Lobo Ártico", "tl": "Arctic Wolf"},
    "reindeer": {"es": "Reno", "tl": "Reindeer"},
    "caribou": {"es": "Caribú", "tl": "Caribou"},
    "musk_ox": {"es": "Buey Almizclero", "tl": "Musk Ox"},
    "lemming": {"es": "Lemming", "tl": "Lemming"},
    "walrus": {"es": "Morsa", "tl": "Walrus"},
    "harp_seal": {"es": "Foca Arpa", "tl": "Harp Seal"},
    "harbor_seal": {"es": "Foca Común", "tl": "Harbor Seal"},
    "beluga_whale": {"es": "Ballena Beluga", "tl": "Beluga Whale"},
    "narwhal": {"es": "Narval", "tl": "Narwhal"},
    "bowhead_whale": {"es": "Ballena Bowhead", "tl": "Bowhead Whale"},
    "sperm_whale": {"es": "Cachalote", "tl": "Sperm Whale"},
    "elephant_seal": {"es": "Foca Elefante", "tl": "Elephant Seal"},
    "leopard_seal": {"es": "Foca Leopardo", "tl": "Leopard Seal"},
    "weddell_seal": {"es": "Foca de Weddell", "tl": "Weddell Seal"},
    "emperor_penguin": {"es": "Pingüino Emperador", "tl": "Emperor Penguin"},
    "adelie_penguin": {"es": "Pingüino Adelia", "tl": "Adelie Penguin"},
    "rockhopper_penguin": {"es": "Pingüino Saltarrocas", "tl": "Rockhopper Penguin"},
    "krill_antarctic": {"es": "Krill Antártico", "tl": "Krill Antarctic"},
    "snow_goose": {"es": "Ganso Nival", "tl": "Snow Goose"},
    "ptarmigan": {"es": "Lagópodo", "tl": "Ptarmigan"},
    "puffin": {"es": "Frailecillo", "tl": "Puffin"},
    "clownfish": {"es": "Pez Payaso", "tl": "Clownfish"},
    "angelfish": {"es": "Pez Ángel", "tl": "Angelfish"},
    "jellyfish": {"es": "Medusa", "tl": "Duyong"},
    "starfish": {"es": "Estrella de Mar", "tl": "Starfish"},
    "seahorse": {"es": "Caballito de Mar", "tl": "Seahorse"},
    "sea_turtle": {"es": "Tortuga Marina", "tl": "Pawikan"},
    "lobster": {"es": "Langosta", "tl": "Lobster"},
    "hermit_crab": {"es": "Cangrejo Ermitaño", "tl": "Hermit Crab"},
    "brain_coral": {"es": "Coral Cerebro", "tl": "Brain Coral"},
    "sea_anemone": {"es": "Anémona de Mar", "tl": "Sea Anemone"},
    "butterflyfish": {"es": "Pez Mariposa", "tl": "Butterflyfish"},
    "blue_tang": {"es": "Cirujano Azul", "tl": "Blue Tang"},
    "mandarinfish": {"es": "Pez Mandarín", "tl": "Mandarinfish"},
    "moorish_idol": {"es": "Ídolo Moro", "tl": "Moorish Idol"},
    "parrotfish": {"es": "Pez Loro", "tl": "Parrotfish"},
    "triggerfish": {"es": "Pez Ballesta", "tl": "Triggerfish"},
    "lionfish": {"es": "Pez León", "tl": "Lionfish"},
    "manta_ray": {"es": "Manta Raya", "tl": "Manta Ray"},
    "stingray": {"es": "Raya", "tl": "Pagi"},
    "reef_shark": {"es": "Tiburón de Arrecife", "tl": "Reef Shark"},
    "hammerhead_shark": {"es": "Tiburón Martillo", "tl": "Hammerhead Shark"},
    "great_white_shark": {"es": "Tiburón Blanco", "tl": "Great White Shark"},
    "tiger_shark": {"es": "Tiburón Tigre", "tl": "Tiger Shark"},
    "sea_urchin": {"es": "Erizo de Mar", "tl": "Sea Urchin"},
    "octopus": {"es": "Pulpo", "tl": "Pugita"},
    "cuttlefish": {"es": "Sepia", "tl": "Cuttlefish"},
    "moray_eel": {"es": "Morena", "tl": "Moray Eel"},
    "pufferfish": {"es": "Pez Globo", "tl": "Pufferfish"},
    "bottlenose_dolphin": {"es": "Delfín Nariz de Botella", "tl": "Bottlenose Dolphin"},
    "orca": {"es": "Orca", "tl": "Orca"},
    "sea_lion": {"es": "León Marino", "tl": "Sea Lion"},
    "sea_otter": {"es": "Nutria Marina", "tl": "Sea Otter"},
    "goblin_shark": {"es": "Tiburón Duende", "tl": "Goblin Shark"},
    "frilled_shark": {"es": "Tiburón Fraile", "tl": "Frilled Shark"},
    "dragonfish": {"es": "Pez Dragón", "tl": "Dragonfish"},
    "viperfish": {"es": "Pez Víbora", "tl": "Viperfish"},
    "fangtooth": {"es": "Pez Diente de Colmillo", "tl": "Fangtooth"},
    "gulper_eel": {"es": "Anguila Gulpadora", "tl": "Gulper Eel"},
    "hatchetfish": {"es": "Pez Hacha", "tl": "Hatchetfish"},
    "lanternfish": {"es": "Pez Linterna", "tl": "Lanternfish"},
    "barreleye": {"es": "Pez Ojo de Barril", "tl": "Barreleye"},
    "coffinfish": {"es": "Pez Ataúd", "tl": "Coffinfish"},
    "oarfish": {"es": "Pez Remo", "tl": "Oarfish"},
    "colossal_squid": {"es": "Calamar Colosal", "tl": "Colossal Squid"},
    "cookiecutter_shark": {"es": "Tiburón Galleta", "tl": "Cookiecutter Shark"},
    "six_gill_shark": {"es": "Tiburón de Seis Branquias", "tl": "Six Gill Shark"},
    "grenadier_fish": {"es": "Granadero", "tl": "Grenadier Fish"},
    "lizardfish": {"es": "Pez Lagarto", "tl": "Lizardfish"},
    "snipe_eel": {"es": "Anguila Aguja", "tl": "Snipe Eel"},
    "cusk_eel": {"es": "Anguila Cusk", "tl": "Cusk Eel"},
    "chimaera": {"es": "Quimera", "tl": "Chimaera"},
    "ghost_shark": {"es": "Tiburón Fantasma", "tl": "Ghost Shark"},
    "spookfish": {"es": "Pez Fantasma", "tl": "Spookfish"},
    "wolffish": {"es": "Pez Lobo", "tl": "Wolffish"},
    "mariana_snailfish": {"es": "Pez Caracol de las Marianas", "tl": "Mariana Snailfish"},
    "faceless_cusk": {"es": "Cusk Sin Rostro", "tl": "Faceless Cusk"},
    "black_swallower": {"es": "Tragador Negro", "tl": "Black Swallower"},
    "deep_sea_jellyfish": {"es": "Medusa de Profundidad", "tl": "Deep Sea Jellyfish"},
    "comb_jelly": {"es": "Medusa Peine", "tl": "Comb Jelly"},
    "abyssal_spiderfish": {"es": "Pez Araña Abisal", "tl": "Abyssal Spiderfish"},
    "beaked_whale": {"es": "Ballena Pico", "tl": "Beaked Whale"},
    "big_red_jelly": {"es": "Medusa Roja Gigante", "tl": "Big Red Jelly"},
    "brisingid_starfish": {"es": "Estrella de Mar Brisingida", "tl": "Brisingid Starfish"},
    "flashlight_fish": {"es": "Pez Linterna", "tl": "Flashlight Fish"},
    "salamander": {"es": "Salamandra", "tl": "Salamander"},
    "eagle": {"es": "Águila", "tl": "Aguila"},
    "hummingbird": {"es": "Colibrí", "tl": "Ibon na Hummingbird"},
    "cockatiel": {"es": "Cacatúa Ninfa", "tl": "Cockatiel"},
    "parakeet": {"es": "Periquito", "tl": "Parakeet"},
    "cardinal": {"es": "Cardenal", "tl": "Cardinal"},
    "blue_jay": {"es": "Arrendajo Azul", "tl": "Blue Jay"},
    "pelican": {"es": "Pelícano", "tl": "Pelikano"},
    "seagull": {"es": "Gaviota", "tl": "Seagull"},
    "albatross": {"es": "Albatros", "tl": "Albatross"},
    "turkey_vulture": {"es": "Zopilote", "tl": "Turkey Vulture"},
    "penguin": {"es": "Pingüino", "tl": "Penguin"},
    "snowy_owl": {"es": "Búho Níveo", "tl": "Snowy Owl"},
    "parrot": {"es": "Loro", "tl": "Loro"},
    "macaw": {"es": "Guacamayo", "tl": "Macaw"},
    "toucan": {"es": "Tucán", "tl": "Toucan"},
    "barn_owl": {"es": "Lechuza", "tl": "Barn Owl"},
    "great_horned_owl": {"es": "Búho Cornudo", "tl": "Great Horned Owl"},
    "border_collie": {"es": "Border Collie", "tl": "Border Collie"},
    "golden_retriever": {"es": "Golden Retriever", "tl": "Golden Retriever"},
    "coyote": {"es": "Coyote", "tl": "Coyote"},
    "wolf": {"es": "Lobo", "tl": "Lobo"},
    "siamese_cat": {"es": "Gato Siamés", "tl": "Siamese Cat"},
    "tabby_cat": {"es": "Gato Atigrado", "tl": "Tabby Cat"},
    "bengal_tiger": {"es": "Tigre de Bengala", "tl": "Bengal Tiger"},
    "bobcat": {"es": "Lince Rojo", "tl": "Bobcat"},
    "lynx": {"es": "Lince", "tl": "Lynx"},
    "leopard": {"es": "Leopardo", "tl": "Leopardo"},
    "jaguar": {"es": "Jaguar", "tl": "Jaguar"},
    "moth": {"es": "Polilla", "tl": "Gamugamo"},
    "tarantula": {"es": "Tarántula", "tl": "Tarantula"},
    "firefly": {"es": "Luciérnaga", "tl": "Alitaptap"},
    "leafcutter_ant": {"es": "Hormiga Cortadora de Hojas", "tl": "Leafcutter Ant"},
    "turtle": {"es": "Tortuga", "tl": "Pagong"},
}

manifest_path = "web/data/manifest.json"
with open(manifest_path) as f:
    manifest = json.load(f)

updated = 0
missing = []
for cat in manifest["categories"]:
    for page in cat["pages"]:
        for a in page["animals"]:
            if not a or not a.get("id"):
                continue
            aid = a["id"]
            if aid in translations:
                a["name"]["es"] = translations[aid]["es"]
                a["name"]["tl"] = translations[aid]["tl"]
                updated += 1
            else:
                missing.append(aid)

with open(manifest_path, "w") as f:
    json.dump(manifest, f, ensure_ascii=False, indent=2)

print(f"Updated {updated} animals")
if missing:
    print(f"Missing translations for: {missing}")
